# Generated by Django 4.2 on 2024-10-31 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=64)),
                ('device_key', models.CharField(max_length=100, unique=True)),
                ('phone_no', models.CharField(max_length=17)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='firmware/')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcu_ota_web.userdevice')),
            ],
        ),
    ]
